### ISSUE TITLE
File Hierarchy & Naming convention

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Prosjekt-Spill-H22#19]
Our current file hierarchy is bit bad, in my opinion.
- Unity already has built in quick searches for file types (prefabs, materials, scripts, etc.)
- Having to navigate between many different folders when working on a single gameobject just because it has different types of components is annoying
- Naming conventions are harder to follow (and often not even used!)

We should rather sort files by
- Deciding on and following a good naming convention, to provide ease of access thorugh the asset search bar.
- Organize folders and package according to features rather than file type.

**Comment by Fueredoriku** [comment]
During last meeting, it was democratically concluded that we will ingore this issue until January, and then reassess the situation then

**Comment by Fueredoriku** [comment]
Naming conventions have been decided on today's meetin (01.03.2023), a separate issue,  , for updating repository to match this is now up.

The concentions are as follows:

Files and folders:
- PascalCase

Types (classes/structs):
- PascalCase

Interfaces:
- IPascalCase

Methods:
- PascalCase

Local functions (i.e. nested):
- camelCase

Properties:
- PascalCase

Local variables:
- camelCase

Local constants:
- camelCase

Parameters:
- camelCase

Fields (not private):
- PascalCase

Fields (private):
- camelCase

Static fields (private):
- camelCase

Constant fields:
- SCREAMING_SNAKE_CASE

Static readonly fields (not private):
- PascalCase

Static readonly fields (private):
- camelCase

Enum members:
- SCREAMING_SNAKE_CASE

**Comment by ddabble** [comment]
Just testing the newly added workflows :)) (in this specific case: [`project-add-issue.yml`](https://github.com/hackerspace-ntnu/Prosjekt-Spill-H22/actions/workflows/project-add-issue.yml))
