### ISSUE TITLE
2 new augments of each type

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Prosjekt-Spill-H22#26]
To test out the practical development side of the new augment system, it was decided that someone *other* than @SondreHus should try to implement some augments. (The game need more augments too, ofc)

- [ ] Augment of each type (Alex)
  - [ ] Body augment
  - [x] Barrel augment
  - [x] Extension augment
- [ ] Augment of each type (Thomas)
  - [ ] Body augment
  - [ ] Barrel augment
  - [ ] Extension augment

**Comment by toberge** [comment]
Technically I've done most of this, though I only implemented some that were already modeled, so I'd consider this issue to be a different thing entirely :)
