### ISSUE TITLE
Settle on a theme and artstyle

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Prosjekt-Spill-H22#28]
Decide on the theme and artstyle of the game.

The current theme suggestion(s) are:
- Robot western (Robot cattlepunk)

The current artstyle suggestion(s) are:
- "Toony TF2"-like
- Rusty scrapheap vibes
- Steampunk-like

**Comment by TArchetype** [comment]
Et par til navn:

- Cow-Boy-Tron
- Charlies-Bas-Tards
